local addonName, addon = ...
addon.profiles = addon.profiles ~= nil and addon.profiles or {}

-- General Options
--
-- bar:           string        - Default primary bar. Name of the bar on which to display
-- name:          string        - Name of the spell
-- source:       "friendly"     - Default "hostile". Only enabled if the source unit is friendly or hostile
--               "hostile"
--
-- enabledSpecs:  string        - Default all specs. Spec name or group, can list multiple separated by a comma (, )
--                              - "BLOOD", "FDK", "UH", "HAVOC", "VENG", "BALANCE", "FERAL", "GUARDIAN", "RDRUID", "DEVA", "PRES", "AUG", "BM", "MM", "SV", "ARCANE", "FIRE", "FROST", "BREW", "MW", "WW", "HPAL", "PROTPAL", "RET", "DISC", "HPRIEST", "SHADOW", "ASSA", "OUTLAW", "SUB", "ELE", "ENH", "RSHAM", "AFF", "DEMO", "DESTRO", "ARMS", "FURY", "PROTWAR"
--
-- enabledGroups: string        - Default all. The spec group to include, can list multiple separated by a comma (, )
--                              - "Healers", "Tanks", "Melee", "Ranged", "Physical", "Casters"
--
-- text:          string        - Display custom text
-- showUnitName:  true          - Default false. Displays the name of the unit that the aura is affecting (if exists). Overwrites custom text if enabled.
--                false
--
-- clone:         spellID       - Clones all of the settings from the specified spell Id
-- spellType:    "offensive"    - Defines the type of spell. Will use the associated user-defined border colors and sounds.
--               "defensive"
--               "immunity"
--               "reflect"
--               "cc"
--               "ccImmunity"
--               "utility"
------------------------------------------------------------------------------------------------------------------------------
-- Sound Options
--
-- announce:      "friendly"    - Default is false. Play the spell/aura name
--                "hostile
--
-- customSound:    string       - Play a custom sound effect. Must be the name of a sound file located in
--                              - Media\Sounds\SoundEffects\
--
-- targetOnlyCustomSound: bool  - Only play custom sound if you are targetting the affected unit
-- soundPriority: "Off"         - Defaults to Low. Sets the priority for the sound: off, low, medium or high
--                "High"
--                "medium"
--                "Low"
------------------------------------------------------------------------------------------------------------------------------
-- Tracking CDs
--
-- cd:           number         - Cooldown of spell to track

addon.profiles.default = {
    ["castStart"] = {
        [370965] = {name="The Hunt", spellType="offensive", announce="hostile", soundPriority="low"},
        [370966] = {name="The Hunt", spellType="offensive", announce="hostile", soundPriority="low"},
        [203155] = {name="Sniper Shot", spellType="offensive", announce="hostile", soundPriority="low"},
        [365350] = {name="Arcane Surge", spellType="offensive", announce="hostile", soundPriority="medium"},
        [203286] = {name="Greater Pyroblast", spellType="offensive"},
        [375901] = {name="Mindgames", spellType="offensive", announce="hostile", soundPriority="low"},
        [386997] = {name="Soul Rot", spellType="offensive"},
        [353128] = {name="Arcanosphere", spellType="offensive"},
        [353129] = {name="Arcanosphere", spellType="offensive"},


        [234153] = {name="Drain Life", spellType="defensive"},
        [32375] = {name="Mass Dispel", announce="friendly,hostile", soundPriority="low"},
        [64382] = {name="Shattering Throw", announce="friendly,hostile", soundPriority="low"},
        [404977] = {name="Time Skip"},
    },
    ["castSuccess"] = {
        [305392] = {name="Chill Streak", spellType="offensive", announce="hostile", soundPriority="medium"},
        [63560] = {name="Dark Transformation", spellType="offensive", announce="hostile", soundPriority="medium"},
        [49206] = {name="Summon Gargoyle", spellType="offensive", announce="hostile", soundPriority="low"},
        [152279] = {name="Breath of Sindragosa", spellType="offensive", announce="hostile", soundPriority="low"},
        [279302] = {name="Frostwyrm's Fury", spellType="offensive", announce="hostile", soundPriority="low"},
        [145629] = {name="Anti-Magic Zone", spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        [51052] = {name="Anti-Magic Zone", spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        [258925] = {name="Fel Barrage", spellType="offensive"},
        [400185] = {name="Fel Barrage", spellType="offensive"},
        [274837] = {name="Feral Frenzy", spellType="offensive", announce="hostile", soundPriority="low"},
        [202770] = {name="Fury of Elune", spellType="offensive"},
        [403631] = {name="Breath of Eons", spellType="offensive", announce="hostile", soundPriority="low"},
        [357210] = {name="Deep Breath", spellType="offensive", announce="hostile", soundPriority="medium"},
        [370452] = {name="Shattering Star", spellType="offensive"},
        [203415] = {name="Fury of the Eagle", spellType="offensive"},
        [359844] = {name="Call of the Wild", spellType="offensive", announce="hostile", soundPriority="medium"},
        [321507] = {name="Touch of the Magi", spellType="offensive", announce="hostile", soundPriority="low"},
        [123904] = {name="Invoke Xuen, the White Tiger", spellType="offensive", announce="hostile", soundPriority="low"},
        [113656] = {name="Fists of Fury", spellType="offensive"},
        [137639] = {name="Storm, Earth, and Fire", spellType="offensive", announce="hostile", soundPriority="medium"},
        [138130] = {name="Storm, Earth, and Fire", spellType="offensive", announce="hostile", soundPriority="medium"},
        [122470] = {name="Touch of Karma", spellType="reflect", announce="hostile", soundPriority="medium"},
        [124280] = {name="Touch of Karma", spellType="reflect", announce="hostile", soundPriority="medium"},
        [125174] = {name="Touch of Karma", spellType="reflect", announce="hostile", soundPriority="medium"},
        [375576] = {name="Divine Toll", spellType="offensive"},
        [211522] = {name="Psyfiend", spellType="offensive", announce="hostile", soundPriority="medium"},
        [205021] = {name="Ray of Frost", spellType="offensive", announce="hostile", soundPriority="low"},
        [228260] = {name="Void Eruption", spellType="offensive", announce="hostile", soundPriority="medium"},
        [205179] = {name="Phantom Singularity", spellType="offensive", announce="hostile", soundPriority="medium"},
        [360194] = {name="Deathmark", spellType="offensive", announce="hostile", soundPriority="medium"},
        [280719] = {name="Secret Technique", spellType="offensive", announce="hostile", soundPriority="low"},
        [282449] = {name="Secret Technique", spellType="offensive", announce="hostile", soundPriority="low"},
        [5938] = {name="Shiv", spellType="offensive"},
        [320125] = {name="Echoing Shock", spellType="offensive"},
        [204330] = {name="Skyfury Totem", spellType="offensive"},
        [198067] = {name="Fire Elemental", spellType="offensive", announce="hostile", soundPriority="medium"},        
        [375982] = {name="Primordial Wave", spellType="offensive", announce="hostile", soundPriority="low"},
        [428332] = {name="Primordial Wave", spellType="offensive", announce="hostile", soundPriority="low"},
        [205180] = {name="Summon Darkglare", spellType="offensive", announce="hostile", soundPriority="medium"},
        [265187] = {name="Summon Demonic Tyrant", spellType="offensive", announce="hostile", soundPriority="low"},
        [111898] = {name="Grimoire: Felguard", spellType="offensive", announce="hostile", soundPriority="medium"},
        [1122] = {name="Summon Infernal", spellType="offensive", announce="hostile", soundPriority="medium"},
        [201996] = {name="Summon Observer", spellType="offensive"},
        [198817] = {name="Sharpen Blade", spellType="offensive", announce="hostile", soundPriority="low"},
        [376079] = {name="Spear of Bastion", spellType="offensive"},
        [740] = {name="Tranquility", spellType="immunity"},
        [157982] = {name="Tranquility", spellType="immunity"},
        [236320] = {name="War Banner", spellType="offensive"},
        
        
        [108280] = {name="Healing Tide Totem", spellType="defensive", announce="hostile", soundPriority="medium"},
        [198838] = {name="Earthen Wall Totem", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [98008] = {name="Spirit Link Totem", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [325174] = {name="Spirit Link Totem", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [47536] = {name="Rapture", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [391124] = {name="Restitution", spellType="defensive"},
        [62618] = {name="Power Word: Barrier", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [108968] = {name="Void Shift", spellType="defensive", announce="hostile", announce="friendly,hostile", soundPriority="high"},
        [208683] = {name="Gladiator's Medallion", spellType="defensive", announce="hostile", soundPriority="medium"},
        [336126] = {name="Gladiator's Medallion", spellType="defensive", announce="hostile", soundPriority="medium"},
        [408557] = {name="Phase Shift", spellType="defensive"},


        [48018] = {name="Demonic Circle"},
        [48020] = {name="Demonic Circle: Teleport", announce="friendly,hostile", soundPriority="low"},
        [389713] = {name="Displacement"},
        [30449] = {name="Spellsteal"},
        [101643] = {name="Transcendence"},
        [434763] = {name="Transcendence"},
        [119996] = {name="Transcendence: Transfer", announce="friendly,hostile", soundPriority="low"},
        [434766] = {name="Transcendence: Transfer", announce="friendly,hostile", soundPriority="low"},
        [1856] = {name="Vanish"},
        [32379] = {name="Shadow Word: Death"},        
        [22734] = {name="Drink", announce="hostile", soundPriority="low"},
    }, 
    ["cooldowns"] = {
        [47528] = {name="Mind Freeze", spellType="cooldown", cd="15"},
        [183752] = {name="Disrupt", spellType="cooldown", cd="15"},
        [106839] = {name="Skull Bash", spellType="cooldown", cd="15"},
        [93985] = {name="Skull Bash", spellType="cooldown", cd="15"},        
        [351338] = {name="Quell", spellType="cooldown", cd="20"},
        [147362] = {name="Counter Shot", spellType="cooldown", cd="24"},
        [2139] = {name="Counterspell", spellType="cooldown", cd="20"},
        [96231] = {name="Rebuke", spellType="cooldown", cd="15"},
        [1766] = {name="Kick", spellType="cooldown", cd="15"},
        [116705] = {name="Spear Hand Strike", spellType="cooldown", cd="15"},
        [57994] = {name="Wind Shear", spellType="cooldown", cd="12"},
        [119910] = {name="Spell Lock", spellType="cooldown", cd="15"},
        [19647] = {name="Spell Lock (Felhunter)", spellType="cooldown", cd="15"},
        [119911] = {name="Optical Blast (Command Demon)", spellType="cooldown", cd="15"},
        [115781] = {name="Optical Blast (Observer)", spellType="cooldown", cd="15"},
        [132409] = {name="Spell Lock (Grimoire of Sacrifice)", spellType="cooldown", cd="15"},
        [171138] = {name="Shadow Lock (Doomguard)", spellType="cooldown", cd="15"},
        [171139] = {name="Shadow Lock (Grimoire of Sacrifice)", spellType="cooldown", cd="15"},
        [171140] = {name="Shadow Lock (Command Demon)", spellType="cooldown", cd="15"},		
        [6552] = {name="Pummel", spellType="cooldown", cd="14"},
        [408] = {name="Kidney Shot", spellType="cooldown", cd="30"},
    }, 
    ["auras"] = {
        [383269] = {name="Abomination Limb", spellType="offensive"},
        [383312] = {name="Abomination Limb", ignore="true"},
        [383313] = {name="Abomination Limb", ignore="true"},
        [377587] = {name="Ghoulish Frenzy", spellType="offensive"},
        [377588] = {name="Ghoulish Frenzy", spellType="offensive"},
        [207289] = {name="Unholy Assault", spellType="offensive", announce="hostile", soundPriority="medium"},
        [51271] = {name="Pillar of Frost", spellType="offensive", announce="hostile", soundPriority="medium"},
        [196770] = {name="Remorseless Winter", spellType="offensive"},
        [211793] = {name="Remorseless Winter", spellType="offensive"},
        [208195] = {name="Demon Soul", spellType="offensive"},
        [347765] = {name="Demon Soul", spellType="offensive"},
        [191427] = {name="Metamorphosis", spellType="offensive", announce="hostile", soundPriority="medium"},
        [187827] = {name="Metamorphosis", spellType="offensive", announce="hostile", soundPriority="medium"},
        [162264] = {name="Metamorphosis", spellType="offensive", announce="hostile", soundPriority="medium"},
        [247121] = {name="Metamorphosis", spellType="offensive", announce="hostile", soundPriority="medium"},
        [200166] = {name="Metamorphosis", spellType="offensive", announce="hostile", soundPriority="medium"},
        [106951] = {name="Berserk", spellType="offensive", announce="hostile", soundPriority="low"},
        [50334] = {name="Berserk", spellType="offensive", announce="hostile", soundPriority="low"},
        [383410] = {name="Celestial Alignment", spellType="offensive"},
        [194223] = {name="Celestial Alignment", spellType="offensive"},
        [102543] = {name="Incarnation: Avatar of Ashamane", spellType="offensive", announce="hostile", soundPriority="medium"},
        [252071] = {name="Incarnation: Avatar of Ashamane", spellType="offensive", announce="hostile", soundPriority="medium"},
        [390414] = {name="Incarnation: Chosen of Elune", spellType="offensive", announce="hostile", soundPriority="medium"},
        [102560] = {name="Incarnation: Chosen of Elune", spellType="offensive", announce="hostile", soundPriority="medium"},
        [203052] = {name="Incarnation: King of the Jungle", spellType="offensive", announce="hostile", soundPriority="medium"},
        [375087] = {name="Dragonrage", spellType="offensive", announce="hostile", soundPriority="medium"},
        [370553] = {name="Tip the Scales", spellType="offensive", announce="hostile", soundPriority="low"},
        [19574] = {name="Bestial Wrath", spellType="offensive"},
        [186254] = {name="Bestial Wrath", spellType="offensive"},
        [360952] = {name="Coordinated Assault", spellType="offensive", announce="hostile", soundPriority="medium"},
        [361738] = {name="Coordinated Assault", spellType="offensive", announce="hostile", soundPriority="medium"},
        [361736] = {name="Coordinated Assault", spellType="offensive", announce="hostile", soundPriority="medium"},
        [288613] = {name="Trueshot", spellType="offensive", announce="hostile", soundPriority="medium"},
        [190319] = {name="Combustion", spellType="offensive", announce="hostile", soundPriority="medium"},
        [12472] = {name="Icy Veins", spellType="offensive", announce="hostile", soundPriority="medium"},
        [198144] = {name="Icy Veins", spellType="offensive", announce="hostile", soundPriority="medium"},
        [152173] = {name="Serenity", spellType="offensive"},
        [31884] = {name="Avenging Wrath", spellType="offensive", announce="hostile", soundPriority="medium"},
        [454351] = {name="Avenging Wrath", spellType="offensive", announce="hostile", soundPriority="medium"},
        [384442] = {name="Avenging Wrath: Might", spellType="offensive", announce="hostile", soundPriority="medium"},
        [343721] = {name="Final Reckoning", spellType="offensive"},
        [197871] = {name="Dark Archangel", spellType="offensive"},
        [197874] = {name="Dark Archangel", spellType="offensive"},
        [10060] = {name="Power Infusion", spellType="offensive", announce="friendly,hostile", spellType="immunity", soundPriority="low"},
        [194249] = {name="Voidform", spellType="offensive"},
        [13750] = {name="Adrenaline Rush", spellType="offensive", announce="hostile", soundPriority="medium"},
        [385616] = {name="Echoing Reprimand", spellType="offensive"},
        [323560] = {name="Echoing Reprimand", spellType="offensive"},
        [323559] = {name="Echoing Reprimand", spellType="offensive"},
        [354838] = {name="Echoing Reprimand", spellType="offensive"},
        [121471] = {name="Shadow Blades", spellType="offensive", announce="hostile", soundPriority="low"},
        [185313] = {name="Shadow Dance", spellType="offensive", announce="hostile", soundPriority="low"},
        [185422] = {name="Shadow Dance", spellType="offensive", announce="hostile", soundPriority="low"},
        [114050] = {name="Ascendance", spellType="offensive", announce="hostile", soundPriority="medium"},
        [114051] = {name="Ascendance", spellType="offensive", announce="hostile", soundPriority="medium"},
        [114052] = {name="Ascendance", spellType="offensive", announce="hostile", soundPriority="medium"},
        [51533] = {name="Feral Spirit", spellType="offensive", announce="hostile", soundPriority="low"},
        [333957] = {name="Feral Spirit", spellType="offensive", announce="hostile", soundPriority="low"},
        [383009] = {name="Stormkeeper", spellType="offensive"},
        [191634] = {name="Stormkeeper", spellType="offensive"},
        [113860] = {name="Dark Soul: Misery", spellType="offensive"},
        [107574] = {name="Avatar", spellType="offensive", announce="hostile", soundPriority="medium"},
        [401150] = {name="Avatar", spellType="offensive", announce="hostile", soundPriority="medium"},
        [227847] = {name="Bladestorm", spellType="offensive"},
        [389774] = {name="Bladestorm", spellType="offensive"},
        [199261] = {name="Death Wish", spellType="offensive"},
        [1719] = {name="Recklessness", spellType="offensive", announce="hostile", soundPriority="medium"},

    
        [48707] = {name="Anti-Magic Shell", spellType="defensive", announce="hostile", soundPriority="low"},
        [410358] = {name="Anti-Magic Shell", spellType="defensive", announce="hostile", soundPriority="low"},
        [48743] = {name="Death Pact", spellType="defensive"},
        [48792] = {name="Icebound Fortitude", spellType="defensive", announce="hostile", soundPriority="medium"},
        [212800] = {name="Blur", spellType="defensive", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        [196718] = {name="Darkness", spellType="defensive", announce="friendly,hostile", soundPriority="low"},
        [209426] = {name="Darkness", spellType="defensive", announce="friendly,hostile", soundPriority="low"},
        [196555] = {name="Netherwalk", spellType="defensive"},
        [207810] = {name="Nether Bond", spellType="defensive"},
        [206803] = {name="Rain from Above", spellType="defensive"},
        [22812] = {name="Barkskin", spellType="defensive", announce="hostile", soundPriority="low"},
        [102351] = {name="Cenarion Ward", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [102352] = {name="Cenarion Ward", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [102342] = {name="Ironbark", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [61336] = {name="Survival Instincts", spellType="defensive", announce="hostile", soundPriority="medium"},
        [363916] = {name="Obsidian Scales", spellType="defensive", announce="hostile", soundPriority="medium"},
        [374348] = {name="Renewing Blaze", spellType="defensive"},
        [374349] = {name="Renewing Blaze", spellType="defensive"},
        [378441] = {name="Time Stop", spellType="defensive", announce="hostile", soundPriority="medium"},
        [388035] = {name="Fortitude of the Bear", spellType="defensive", announce="hostile", soundPriority="medium"},
        [392956] = {name="Fortitude of the Bear", spellType="defensive", announce="hostile", soundPriority="medium"},
        [34477] = {name="Interlope", spellType="defensive", announce="hostile", soundPriority="low"},
        [53480] = {name="Roar of Sacrifice", spellType="defensive", announce="hostile", soundPriority="low"},
        [264735] = {name="Survival of the Fittest", spellType="defensive", announce="hostile", soundPriority="medium"},
        [122278] = {name="Dampen Harm", spellType="defensive"},
        [122783] = {name="Diffuse Magic", spellType="defensive"},
        [115203] = {name="Fortifying Brew", spellType="defensive", announce="hostile", soundPriority="medium"},
        [120954] = {name="Fortifying Brew", spellType="defensive", announce="hostile", soundPriority="medium"},
        [31850] = {name="Ardent Defender", spellType="defensive"},
        [6940] = {name="Blessing of Sacrifice", spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        [199448] = {name="Blessing of Sacrifice", spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        [210256] = {name="Blessing of Sanctuary", spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        [86659] = {name="Guardian of Ancient Kings", spellType="defensive"},
        [228049] = {name="Guardian of Ancient Kings", spellType="defensive"},
        [212641] = {name="Guardian of Ancient Kings", spellType="defensive"},
        [47788] = {name="Guardian Spirit", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [33206] = {name="Pain Suppression", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [197268] = {name="Ray of Hope", spellType="defensive", announce="hostile", soundPriority="low"},
        [31224] = {name="Cloak of Shadows", spellType="defensive"},
        [108271] = {name="Astral Shift", spellType="defensive",  announce="hostile", soundPriority="medium"},
        [409293] = {name="Burrow", spellType="immunity", announce="hostile", soundPriority="medium"},
        [108416] = {name="Dark Pact", spellType="defensive", announce="hostile", soundPriority="low"},
        [104773] = {name="Unending Resolve", spellType="defensive",announce="hostile", soundPriority="medium"},
        [184364] = {name="Enraged Regeneration", spellType="defensive", announce="hostile", soundPriority="medium"},
        [190456] = {name="Ignore Pain", spellType="defensive"},
        [12975] = {name="Last Stand", spellType="defensive"},
        [97462] = {name="Rallying Cry", spellType="defensive", announce="hostile", soundPriority="low"},
        [97463] = {name="Rallying Cry", spellType="defensive", announce="hostile", soundPriority="low"},
        [871] = {name="Shield Wall", spellType="defensive"},
        [215769] = {name="Spirit of Redemption", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        [27827] = {name="Spirit of Redemption", spellType="defensive", announce="friendly,hostile", soundPriority="high"},
            
            
        [354489] = {name="Glimpse", spellType="immunity", announce="hostile", soundPriority="low"},
        [354610] = {name="Glimpse", spellType="immunity", announce="hostile", soundPriority="low"},
        [157982] = {name="Tranquility", spellType="immunity", announce="hostile", soundPriority="medium"},
        [309326] = {name="Tranquility", spellType="immunity", announce="hostile", soundPriority="medium"},
        [740] = {name="Tranquility", spellType="immunity", announce="hostile", soundPriority="medium"},
        [186265] = {name="Aspect of the Turtle", spellType="immunity", announce="hostile", soundPriority="medium"},
        [202748] = {name="Survival Tactics", spellType="immunity", announce="hostile", soundPriority="low"},
        [342245] = {name="Alter Time", spellType="immunity", announce="hostile", soundPriority="medium"},
        [342246] = {name="Alter Time", spellType="immunity", announce="hostile", soundPriority="medium"},
        [45438] = {name="Ice Block", spellType="immunity", announce="hostile", soundPriority="medium"},
        [414658] = {name="Ice Block", spellType="immunity", announce="hostile", soundPriority="medium"},
        [116849] = {name="Life Cocoon", spellType="immunity", announce="hostile", soundPriority="medium"},
        [1022] = {name="Blessing of Protection", spellType="immunity", announce="hostile", soundPriority="medium"},
        [1022] = {name="Blessing of Protection", spellType="immunity", announce="hostile", soundPriority="medium"},
        
        [642] = {name="Divine Shield", spellType="immunity", announce="hostile", soundPriority="medium"},
        [47585] = {name="Dispersion", spellType="immunity", announce="hostile", soundPriority="medium"},
        [199754] = {name="Riposte", spellType="immunity", enabledGroups="physical"},
        [5277] = {name="Evasion", spellType="immunity", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        [208258] = {name="Ethereal Form", spellType="immunity"},
        [118038] = {name="Die by the Sword", spellType="immunity", announce="hostile", soundPriority="medium"},

    
        [200851] = {name="Rage of the Sleeper", spellType="reflect", announce="hostile", soundPriority="medium"},
        [305497] = {name="Thorns", spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        [232559] = {name="Thorns", spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        [184662] = {name="Shield of Vengeance", spellType="reflect", announce="hostile", soundPriority="medium"},
        [403876] = {name="Shield of Vengeance", spellType="reflect", announce="hostile", soundPriority="medium"},
        [23920] = {name="Spell Reflection", spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="casters"},
        [385391] = {name="Spell Reflection", spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="casters"},
        [360827] = {name="Blistering Scales", spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="physical"},
    

        [162480] = {name="Steel Trap", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [162487] = {name="Steel Trap", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [51485] = {name="Earthgrab Totem", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [339] = {name="Entangling Roots", spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        [170855] = {name="Entangling Roots", spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        [19387] = {name="Entrapment", spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        [393456] = {name="Entrapment", spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        [33395] = {name="Freeze", spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        [122] = {name="Frost Nova", spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        [385700] = {name="Frost Nova", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [157997] = {name="Ice Nova", spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        [358385] = {name="Landslide", spellType="cc", nameplate="true", npcDuration="15", playerDuration="6"},
        [355689] = {name="Landslide", spellType="cc", nameplate="true", npcDuration="15", playerDuration="6"},
        [102359] = {name="Mass Entanglement", spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        [247563] = {name="Nature's Grasp", spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        [212638] = {name="Tracker's Net", spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},        
        [3355] = {name="Freezing Trap", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [187650] = {name="Freezing Trap", spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        [203337] = {name="Freezing Trap", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [203340] = {name="Diamond Ice", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [1776] = {name="Gouge", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [2637] = {name="Hibernate", spellType="cc", nameplate="true", npcDuration="40", playerDuration="6"},
        [88625] = {name="Holy Word: Chastise", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [200200] = {name="Holy Word: Chastise", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [200196] = {name="Holy Word: Chastise", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [217832] = {name="Imprison", spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        [221527] = {name="Detainment", spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        [99] = {name="Incapacitating Roar", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [6789] = {name="Mortal Coil", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [115078] = {name="Paralysis", spellType="cc", nameplate="true", npcDuration="60", playerDuration="4"},
        [107079] = {name="Quaking Palm", spellType="cc", nameplate="true", npcDuration="4", playerDuration="2"},
        [6770] = {name="Sap", spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        [213691] = {name="Scatter Shot", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [9484] = {name="Shackle Undead", spellType="cc", nameplate="true", npcDuration="50", playerDuration="5"},
        [51514] = {name="Hex", spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
            [196932] = {name="Voodoo Totem", clone="51514"},
            [51514] = {name="Hex (Frog)", clone="51514"},
            [210873] = {name="Hex (Compy)", clone="51514"},
            [211004] = {name="Hex (Spider)", clone="51514"},
            [211010] = {name="Hex (Snake)", clone="51514"},
            [269352] = {name="Hex (Skeletal Hatchling)", clone="51514"},
            [277778] = {name="Hex (Zandalari Tendonripper)", clone="51514"},
            [277784] = {name="Hex (Wicker Mongrel)", clone="51514"},
            [309328] = {name="Hex (Living Honey)", clone="51514"},
            [211015] = {name="Hex (Cockroach)", clone="51514"},        
        [118] = {name="Polymorph", spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
            [61780] = {name="Polymorph (Turkey)", clone="118"},
            [126819] = {name="Polymorph (Porcupine)", clone="118"},
            [161353] = {name="Polymorph (Polar Bear Cub)", clone="118"},
            [161354] = {name="Polymorph (Monkey)", clone="118"},
            [161355] = {name="Polymorph (Penguin)", clone="118"},
            [28271] = {name="Polymorph (Turtle)", clone="118"},
            [28272] = {name="Polymorph (Pig)", clone="118"},
            [61305] = {name="Polymorph (Black Cat)", clone="118"},
            [61721] = {name="Polymorph (Rabbit)", clone="118"},
            [161372] = {name="Polymorph (Peacock)", clone="118"},
            [277787] = {name="Polymorph (Direhorn)", clone="118"},
            [277792] = {name="Polymorph (Bumblebee)", clone="118"},
            [321395] = {name="Polymorph (Mawrat)", clone="118"},
            [391622] = {name="Polymorph (Duck)", clone="118"},            
        [20066] = {name="Repentance", spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        [113724] = {name="Ring of Frost", spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        [82691] = {name="Ring of Frost", spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        [321329] = {name="Ring of Frost Slow", ignore=true},
        [2094] = {name="Blind", spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        [427773] = {name="Blind", spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        [115750] = {name="Blinding Light", spellType="cc", nameplate="true", npcDuration="6", playerDuration="4"},
        [105421] = {name="Blinding Light", spellType="cc", nameplate="true", npcDuration="6", playerDuration="4"},
        [207167] = {name="Blinding Sleet", spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        [317898] = {name="Blinding Sleet Slow", ignore=true},
        [31661] = {name="Dragon's Breath", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [5246] = {name="Intimidating Shout", spellType="cc", nameplate="true", npcDuration="8", playerDuration="5"},
        [316593] = {name="Intimidating Shout", spellType="cc", nameplate="true", npcDuration="15", playerDuration="5"},
        [316595] = {name="Intimidating Shout", spellType="cc", nameplate="true", npcDuration="15", playerDuration="5"},
        [8122] = {name="Psychic Scream", spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        [6358] = {name="Seduction", spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        [207685] = {name="Sigil of Misery", spellType="cc", nameplate="true", npcDuration="15", playerDuration="3"},
        [207684] = {name="Sigil of Misery Pre-fear circle", ignore=true},
        [33786] = {name="Cyclone", spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        [5782] = {name="Fear", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [118699] = {name="Fear", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [130616] = {name="Fear", spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        [605] = {name="Mind Control", spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        [360806] = {name="Sleep Walk", spellType="cc", nameplate="true", npcDuration="20", playerDuration="4"},
        [198898] = {name="Song of Chi-Ji", spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},
        [198909] = {name="Song of Chi-Ji", spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},
        [1513] = {name="Scare Beast", spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},        
        [163505] = {name="Rake", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [155722] = {name="Rake DoT", ignore="true"},
        [89766] = {name="Axe Toss", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [192058] = {name="Capicator Totem", spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        [179057] = {name="Chaos Nova", spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        [1833] = {name="Cheap Shot", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [211881] = {name="Fel Eruption", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [47481] = {name="Gnaw", spellType="cc", nameplate="true", npcDuration="1", playerDuration="1"},
        [91800] = {name="Gnaw", spellType="cc", nameplate="true", npcDuration="1", playerDuration="1"},
        [853] = {name="Hammer of Justice", spellType="cc", nameplate="true", npcDuration="6", playerDuration="5"},
        [287712] = {name="Haymaker", spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        [19577] = {name="Intimidation", spellType="cc", nameplate="true", npcDuration="5", playerDuration="3"},
        [24394] = {name="Intimidation", spellType="cc", nameplate="true", npcDuration="5", playerDuration="3"},
        [357021] = {name="Consecutive Concussion", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},        
        [408] = {name="Kidney Shot", spellType="cc", nameplate="true", npcDuration="6", playerDuration="5", announce="hostile", soundPriority="medium"},
        [119381] = {name="Leg Sweep", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [305483] = {name="Lightning Lasso", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [305485] = {name="Lightning Lasso", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [305484] = {name="Lightning Lasso", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [22570] = {name="Maim", spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        [203123] = {name="Maim", spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        [5211] = {name="Mighty Bash", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [64044] = {name="Psychic Horror", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [46968] = {name="Shockwave", spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        [132168] = {name="Shockwave", spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        [107570] = {name="Storm Bolt", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [132169] = {name="Storm Bolt", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [20549] = {name="War Stomp", spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},        
        [30283] = {name="Shadowfury", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        [703] = {name="Garrote", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [360830] = {name="Garrote", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [202137] = {name="Sigil of Silence Pre-cast Circle", ignore=true},
        [204490] = {name="Sigil of Silence", spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        [15487] = {name="Silence", spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [78675] = {name="Solar Beam", spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        [356727] = {name="Spider Venom", spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        [236077] = {name="Disarm", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [207777] = {name="Dismantle", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [209749] = {name="Faerie Swarm", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [233759] = {name="Grapple Weapon", spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        [407028] = {name="Sticky Tar Bomb", spellType="cc", nameplate="true", npcDuration="4", playerDuration="5"},
        [407032] = {name="Sticky Tar Bomb", spellType="cc", nameplate="true", npcDuration="4", playerDuration="5"},
        [407031] = {name="Sticky Tar Bomb", spellType="cc", nameplate="true", npcDuration="4", playerDuration="5"},

            
        [49039] = {name="Lichborne", spellType="ccImmunity"},
        [378464] = {name="Nullifying Shroud", spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        [209584] = {name="Zen Focus Tea", spellType="ccImmunity"},
        [213610] = {name="Holy Ward", spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        [204336] = {name="Grounding Totem", spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        [8178] = {name="Grounding Totem", spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        [212295] = {name="Nether Ward", spellType="ccImmunity", announce="hostile", soundPriority="medium"},
    

        [188501] = {name="Spectral Sight"},
        [374968] = {name="Time Spiral"},
            [375234] = {name="Time Spiral", clone="374968"},
            [375238] = {name="Time Spiral", clone="374968"},
            [375240] = {name="Time Spiral", clone="374968"},
            [375258] = {name="Time Spiral", clone="374968"},
            [375254] = {name="Time Spiral", clone="374968"},
            [375257] = {name="Time Spiral", clone="374968"},
            [375229] = {name="Time Spiral", clone="374968"},
            [375230] = {name="Time Spiral", clone="374968"},
            [375252] = {name="Time Spiral", clone="374968"},
            [375226] = {name="Time Spiral", clone="374968"},
            [375253] = {name="Time Spiral", clone="374968"},
            [375256] = {name="Time Spiral", clone="374968"},
            [375255] = {name="Time Spiral", clone="374968"},
        [207736] = {name="Shadowy Duel"},
        [199483] = {name="Camouflage"},
        [110959] = {name="Greater Invisibility"},
        [110960] = {name="Greater Invisibility"},
        [113862] = {name="Greater Invisibility"},
        [66] = {name="Invisibility"},
        [32612] = {name="Invisibility"},
        [414664] = {name="Mass Invisibility"},
        [5215] = {name="Prowl"},
        [24450] = {name="Prowl"},
        [102547] = {name="Prowl"},
        [135201] = {name="Shadowmeld"},
        [58984] = {name="Shadowmeld"},
        [1784] = {name="Stealth"},
        [115191] = {name="Stealth"},
        [118968] = {name="Stealth"},
        [1044] = {name="Blessing of Freedom"},
        [54216] = {name="Master's Call"},
        [53271] = {name="Master's Call"},
        [62305] = {name="Master's Call"},
    },
    ["nameplates"] = {
        ["yOffset"] = 50,
        ["maxIcons"] = 25,
        ["maxDuration"] = 60,
        ["iconSize"] = 34,
        ["iconSpacing"] = 3,
        ["borderSize"] = 2,
        ["backdropSize"] = 3,
        ["borderColor"] = {1, 0, 1, .9},        
        ["backdropColor"] = {0, 0, 0, .4},
        ["innerBorder"] = true,
        ["innerBorderColor"] = {0, 0, 0, .9},
        ["cooldownCounter"] = true,
        ["swipeAlpha"] = .3,
        ["cooldownFontColor"] = {1, 1, 0, 1},
        ["cooldownFontSize"] = 24,
    },
    ["bars"] = {
        ["primary-friendly"] = {
            ["displayName"] = "Friendly Spells", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -209, 
                ["yOfs"] = -177, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["primary-hostile"] = {
            ["displayName"] = "Enemy Spells", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 209, 
                ["yOfs"] = -177, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["cooldowns-friendly"] = {
            ["displayName"] = "Friendly Cooldowns", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -200, 
                ["yOfs"] = -132, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["cooldowns-hostile"] = {
            ["displayName"] = "Enemy Cooldowns", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 200, 
                ["yOfs"] = -132, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }
    }
}
