local addonName, addon = ...
addon.profiles = addon.profiles ~= nil and addon.profiles or {}

-- General Options
--
-- bar:           string        - Default primary bar. Name of the bar on which to display
-- name:          string        - Name of the spell
-- source:       "friendly"     - Default "hostile". Only enabled if the source unit is friendly or hostile
--               "hostile"
--
-- enabledSpecs:  string        - Default all specs. Spec name or group, can list multiple separated by a comma (, )
--                              - "BLOOD", "FDK", "UH", "HAVOC", "VENG", "BALANCE", "FERAL", "GUARDIAN", "RDRUID", "DEVA", "PRES", "AUG", "BM", "MM", "SV", "ARCANE", "FIRE", "FROST", "BREW", "MW", "WW", "HPAL", "PROTPAL", "RET", "DISC", "HPRIEST", "SHADOW", "ASSA", "OUTLAW", "SUB", "ELE", "ENH", "RSHAM", "AFF", "DEMO", "DESTRO", "ARMS", "FURY", "PROTWAR"
--
-- enabledGroups: string        - Default all. The spec group to include, can list multiple separated by a comma (, )
--                              - "Healers", "Tanks", "Melee", "Ranged", "Physical", "Casters"
--
-- text:          string        - Display custom text
-- showUnitName:  true          - Default false. Displays the name of the unit that the aura is affecting (if exists). Overwrites custom text if enabled.
--                false
--
-- clone:         spellID       - Clones all of the settings from the specified spell Id
-- spellType:    "offensive"    - Defines the type of spell. Will use the associated user-defined border colors and sounds.
--               "defensive"
--               "immunity"
--               "reflect"
--               "cc"
--               "ccImmunity"
--               "utility"
------------------------------------------------------------------------------------------------------------------------------
-- Sound Options
--
-- announce:      "friendly"    - Default is false. Play the spell/aura name
--                "hostile
--
-- customSound:    string       - Play a custom sound effect. Must be the name of a sound file located in
--                              - Media\Sounds\SoundEffects\
--
-- targetOnlyCustomSound: bool  - Only play custom sound if you are targetting the affected unit
-- soundPriority: "Off"         - Defaults to Low. Sets the priority for the sound: off, low, medium or high
--                "High"
--                "medium"
--                "Low"
------------------------------------------------------------------------------------------------------------------------------
-- Tracking CDs
--
-- cd:           number         - Cooldown of spell to track

addon.profiles.default = {
    ["castStart"] = {
        ["Aimed Shot"] = {spellType="offensive", announce="friendly,hostile", soundPriority="low"},
        ["The Hunt"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Sniper Shot"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Arcane Surge"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Greater Pyroblast"] = {spellType="offensive"},
        ["Mindgames"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Soul Rot"] = {spellType="offensive"},
        ["Arcanosphere"] = {spellType="offensive"},
        ["Drain Life"] = {spellType="defensive"},
        ["Mass Dispel"] = {announce="friendly,hostile", soundPriority="low"},
        ["Shattering Throw"] = {announce="friendly,hostile", soundPriority="low"},
        ["Time Skip"] = {"Time Skip"},
    },
    ["castSuccess"] = {
        ["Chill Streak"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Dark Transformation"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Summon Gargoyle"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Breath of Sindragosa"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Frostwyrm's Fury"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Anti-Magic Zone"] = {spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        ["Fel Barrage"] = {spellType="offensive"},
        ["Fel Barrage"] = {spellType="offensive"},
        ["Feral Frenzy"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Fury of Elune"] = {spellType="offensive"},
        ["Breath of Eons"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Deep Breath"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Shattering Star"] = {spellType="offensive"},
        ["Fury of the Eagle"] = {spellType="offensive"},
        ["Call of the Wild"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Touch of the Magi"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Fists of Fury"] = {spellType="offensive"},
        ["Invoke Xuen, the White Tiger"] = {spellType="offensive", announce="friendly,hostile", soundPriority="low"},
        ["Storm, Earth, and Fire"] = {"Storm, Earth, and Fire", spellType="offensive", announce="friendly,hostile", soundPriority="medium"},
        ["Touch of Karma"] = {spellType="reflect", announce="hostile", soundPriority="medium"},
        ["Divine Toll"] = {spellType="offensive"},
        ["Psyfiend"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Ray of Frost"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Void Eruption"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Phantom Singularity"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Deathmark"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Secret Technique"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Shiv"] = {spellType="offensive"},
        ["Echoing Shock"] = {spellType="offensive"},
        ["Skyfury Totem"] = {spellType="offensive"},
        ["Fire Elemental"] = {spellType="offensive", announce="hostile", soundPriority="medium"},        
        ["Primordial Wave"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Summon Darkglare"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Summon Demonic Tyrant"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Grimoire: Felguard"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Summon Infernal"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Summon Observer"] = {spellType="offensive"},
        ["Sharpen Blade"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Spear of Bastion"] = {spellType="offensive"},
        ["Tranquility"] = {spellType="immunity"},
        ["War Banner"] = {spellType="offensive"},
        
        
        ["Healing Tide Totem"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Earthen Wall Totem"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Spirit Link Totem"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Rapture"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Restitution"] = {spellType="defensive"},
        ["Power Word: Barrier"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Void Shift"] = {spellType="defensive", announce="hostile", announce="friendly,hostile", soundPriority="high"},
        ["Gladiator's Medallion"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Phase Shift"] = {spellType="defensive"},


        ["Demonic Circle"] = {},
        ["Demonic Circle: Teleport"] = {announce="friendly,hostile", soundPriority="low"},
        ["Displacement"] = {},
        ["Spellsteal"] = {},
        ["Transcendence"] = {},
        ["Transcendence: Transfer"] = {announce="friendly,hostile", soundPriority="low"},
        ["Vanish"] = {},
        ["Shadow Word: Death"] = {},        
        ["Drink"] = {announce="hostile", soundPriority="low"},
    }, 
    ["cooldowns"] = {
        ["Mind Freeze"] = {spellType="cooldown", cd="15"},
        ["Disrupt"] = {spellType="cooldown", cd="15"},
        ["Skull Bash"] = {spellType="cooldown", cd="15"},
        ["Quell"] = {spellType="cooldown", cd="20"},
        ["Counter Shot"] = {spellType="cooldown", cd="24"},
        ["Counterspell"] = {spellType="cooldown", cd="20"},
        ["Rebuke"] = {spellType="cooldown", cd="15"},
        ["Kick"] = {spellType="cooldown", cd="15"},
        ["Spear Hand Strike"] = {spellType="cooldown", cd="15"},
        ["Wind Shear"] = {spellType="cooldown", cd="12"},
        ["Spell Lock"] = {spellType="cooldown", cd="15"},
        ["Optical Blast"] = {spellType="cooldown", cd="15"},
        ["Shadow Lock"] = {spellType="cooldown", cd="15"},
        ["Pummel"] = {spellType="cooldown", cd="14"},
        ["Kidney Shot"] = {spellType="cooldown", cd="30"},
    }, 
    ["auras"] = {

        ["Abomination Limb"] = {spellType="offensive"},
        [383312] = {"Abomination Limb", ignore="true"},
        [383313] = {"Abomination Limb", ignore="true"},

        ["Ghoulish Frenzy"] = {spellType="offensive"},
        ["Unholy Assault"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Pillar of Frost"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Remorseless Winter"] = {spellType="offensive"},
        ["Demon Soul"] = {spellType="offensive"},
        ["Metamorphosis"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Berserk"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Celestial Alignment"] = {spellType="offensive"},
        ["Incarnation: Avatar of Ashamane"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Incarnation: Chosen of Elune"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Incarnation: King of the Jungle"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Dragonrage"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Tip the Scales"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Bestial Wrath"] = {spellType="offensive"},
        ["Coordinated Assault"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Trueshot"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Combustion"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Icy Veins"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Serenity"] = {spellType="offensive"},
        ["Avenging Wrath"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Avenging Wrath"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Avenging Wrath: Might"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Final Reckoning"] = {spellType="offensive"},
        ["Dark Archangel"] = {spellType="offensive"},
        ["Dark Archangel"] = {spellType="offensive"},
        ["Power Infusion"] = {spellType="offensive", announce="friendly,hostile", spellType="immunity", soundPriority="low"},
        ["Voidform"] = {spellType="offensive"},
        ["Adrenaline Rush"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Echoing Reprimand"] = {spellType="offensive"},
        ["Shadow Blades"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Shadow Dance"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Ascendance"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Feral Spirit"] = {spellType="offensive", announce="hostile", soundPriority="low"},
        ["Stormkeeper"] = {spellType="offensive"},
        ["Dark Soul: Misery"] = {spellType="offensive"},
        ["Avatar"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
        ["Bladestorm"] = {spellType="offensive"},
        ["Death Wish"] = {spellType="offensive"},
        ["Recklessness"] = {spellType="offensive", announce="hostile", soundPriority="medium"},
    
        ["Anti-Magic Shell"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Death Pact"] = {spellType="defensive"},
        ["Icebound Fortitude"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Blur"] = {spellType="defensive", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        ["Darkness"] = {spellType="defensive", announce="friendly,hostile", soundPriority="low"},
        ["Netherwalk"] = {spellType="defensive"},
        ["Nether Bond"] = {spellType="defensive"},
        ["Rain from Above"] = {spellType="defensive"},
        ["Barkskin"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Cenarion Ward"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Ironbark"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Survival Instincts"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Obsidian Scales"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Renewing Blaze"] = {spellType="defensive"},
        ["Time Stop"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Fortitude of the Bear"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Interlope"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Roar of Sacrifice"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Survival of the Fittest"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Dampen Harm"] = {spellType="defensive"},
        ["Diffuse Magic"] = {spellType="defensive"},
        ["Fortifying Brew"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Ardent Defender"] = {spellType="defensive"},
        ["Blessing of Sacrifice"] = {spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        ["Blessing of Sanctuary"] = {spellType="defensive", announce="friendly,hostile", soundPriority="medium"},
        ["Guardian of Ancient Kings"] = {spellType="defensive"},
        ["Guardian Spirit"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Pain Suppression"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
        ["Ray of Hope"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Cloak of Shadows"] = {spellType="defensive"},
        ["Astral Shift"] = {spellType="defensive",  announce="hostile", soundPriority="medium"},
        ["Burrow"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Dark Pact"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Unending Resolve"] = {spellType="defensive",announce="hostile", soundPriority="medium"},
        ["Enraged Regeneration"] = {spellType="defensive", announce="hostile", soundPriority="medium"},
        ["Ignore Pain"] = {spellType="defensive"},
        ["Last Stand"] = {spellType="defensive"},
        ["Rallying Cry"] = {spellType="defensive", announce="hostile", soundPriority="low"},
        ["Shield Wall"] = {spellType="defensive"},
        ["Spirit of Redemption"] = {spellType="defensive", announce="friendly,hostile", soundPriority="high"},
                      
        ["Glimpse"] = {spellType="immunity", announce="hostile", soundPriority="low"},
        ["Tranquility"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Aspect of the Turtle"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Survival Tactics"] = {spellType="immunity", announce="hostile", soundPriority="low"},
        ["Alter Time"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Ice Block"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Life Cocoon"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Blessing of Protection"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        
        ["Divine Shield"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Dispersion"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
        ["Riposte"] = {spellType="immunity", enabledGroups="physical"},
        ["Evasion"] = {spellType="immunity", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        ["Ethereal Form"] = {spellType="immunity"},
        ["Die by the Sword"] = {spellType="immunity", announce="hostile", soundPriority="medium"},
    
        ["Rage of the Sleeper"] = {spellType="reflect", announce="hostile", soundPriority="medium"},
        ["Thorns"] = {spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="physical"},
        ["Shield of Vengeance"] = {spellType="reflect", announce="hostile", soundPriority="medium"},
        ["Spell Reflection"] = {spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="casters"},
        ["Blistering Scales"] = {spellType="reflect", announce="hostile", soundPriority="medium", enabledGroups="physical"},
    
        ["Steel Trap"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        ["Earthgrab Totem"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        ["Entangling Roots"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        ["Entangling Roots"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        ["Entrapment"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        ["Freeze"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        ["Frost Nova"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        ["Ice Nova"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        ["Landslide"] = {spellType="cc", nameplate="true", npcDuration="15", playerDuration="6"},
        ["Mass Entanglement"] = {spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        ["Nature's Grasp"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        ["Tracker's Net"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},        
        ["Freezing Trap"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Diamond Ice"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Gouge"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        ["Hibernate"] = {spellType="cc", nameplate="true", npcDuration="40", playerDuration="6"},
        ["Holy Word: Chastise"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Holy Word: Chastise"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Holy Word: Chastise"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Imprison"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        ["Detainment"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        ["Incapacitating Roar"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        ["Mortal Coil"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        ["Paralysis"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="4"},
        ["Quaking Palm"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="2"},
        ["Sap"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        ["Scatter Shot"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Shackle Undead"] = {spellType="cc", nameplate="true", npcDuration="50", playerDuration="5"},
        ["Hex"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        ["Polymorph"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        ["Repentance"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        ["Ring of Frost"] = {spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        [321329] = {"Ring of Frost Slow", ignore=true},
        ["Blind"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        ["Blinding Light"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="4"},
        ["Blinding Sleet"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        [317898] = {"Blinding Sleet Slow", ignore=true},
        ["Dragon's Breath"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        ["Intimidating Shout"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="5"},
        ["Psychic Scream"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        ["Seduction"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        ["Sigil of Misery"] = {spellType="cc", nameplate="true", npcDuration="15", playerDuration="3"},
        [207684] = {"Sigil of Misery Pre-fear circle", ignore=true},
        ["Cyclone"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        ["Fear"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        ["Mind Control"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        ["Sleep Walk"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="4"},
        ["Song of Chi-Ji"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},
        ["Scare Beast"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},        
        ["Rake"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        [155722] = {"Rake DoT", ignore="true"},        
        ["Axe Toss"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Capicator Totem"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        ["Chaos Nova"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        ["Cheap Shot"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        ["Fel Eruption"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Gnaw"] = {spellType="cc", nameplate="true", npcDuration="1", playerDuration="1"},
        ["Hammer of Justice"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="5"},
        ["Haymaker"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        ["Intimidation"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="3"},
        ["Consecutive Concussion"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},        
        ["Kidney Shot"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="5", announce="hostile", soundPriority="medium"},
        ["Leg Sweep"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        ["Lightning Lasso"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Maim"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        ["Mighty Bash"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        ["Psychic Horror"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Shockwave"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        ["Storm Bolt"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["War Stomp"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},        
        ["Shadowfury"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        ["Garrote"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        [202137] = {"Sigil of Silence Pre-cast Circle", ignore=true},
        ["Sigil of Silence"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        ["Silence"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        ["Solar Beam"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        ["Spider Venom"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        ["Disarm"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Dismantle"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Faerie Swarm"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Grapple Weapon"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        ["Sticky Tar Bomb"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="5"},
            
        ["Lichborne"] = {spellType="ccImmunity"},
        ["Nullifying Shroud"] = {spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        ["Zen Focus Tea"] = {spellType="ccImmunity"},
        ["Holy Ward"] = {spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        ["Grounding Totem"] = {spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        ["Grounding Totem"] = {spellType="ccImmunity", announce="hostile", soundPriority="medium"},
        ["Nether Ward"] = {spellType="ccImmunity", announce="hostile", soundPriority="medium"},
    
        ["Spectral Sight"] = {spellType="utility", announce="hostile"},
        ["Time Spiral"] = {spellType="utility", announce="hostile"},
        ["Shadowy Duel"] = {spellType="utility", announce="hostile"},
        ["Camouflage"] = {spellType="utility", announce="hostile"},
        ["Greater Invisibility"] = {spellType="utility", announce="hostile"},
        ["Invisibility"] = {spellType="utility", announce="hostile"},
        ["Mass Invisibility"] = {spellType="utility", announce="hostile"},
        ["Prowl"] = {spellType="utility", announce="hostile"},
        ["Shadowmeld"] = {spellType="utility", announce="hostile"},
        ["Stealth"] = {spellType="utility", announce="hostile"},
        ["Blessing of Freedom"] = {spellType="utility", announce="hostile"},
        ["Master's Call"] = {spellType="utility", announce="hostile"},
    },
    ["nameplates"] = {
        ["yOffset"] = 50,
        ["maxIcons"] = 25,
        ["maxDuration"] = 60,
        ["iconSize"] = 34,
        ["iconSpacing"] = 3,
        ["borderSize"] = 2,
        ["backdropSize"] = 3,
        ["borderColor"] = {1, 0, 1, .9},        
        ["backdropColor"] = {0, 0, 0, .4},
        ["innerBorder"] = true,
        ["innerBorderColor"] = {0, 0, 0, .9},
        ["cooldownCounter"] = true,
        ["swipeAlpha"] = .3,
        ["cooldownFontColor"] = {1, 1, 0, 1},
        ["cooldownFontSize"] = 24,
    },
    ["bars"] = {
        ["primary-friendly"] = {
            ["displayName"] = "Friendly Spells", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -209, 
                ["yOfs"] = -177, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["primary-hostile"] = {
            ["displayName"] = "Enemy Spells", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 209, 
                ["yOfs"] = -177, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["cooldowns-friendly"] = {
            ["displayName"] = "Friendly Cooldowns", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -200, 
                ["yOfs"] = -132, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["cooldowns-hostile"] = {
            ["displayName"] = "Enemy Cooldowns", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 200, 
                ["yOfs"] = -132, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }
    }
}
