local addonName, addon = ...
addon.profiles = addon.profiles ~= nil and addon.profiles or {}

-- General Options
--
-- bar:           string        - Default primary bar. Name of the bar on which to display
-- name:          string        - Name of the spell
-- source:       "friendly"     - Default "hostile". Only enabled if the source unit is friendly or hostile
--               "hostile"
--
-- enabledSpecs:  string        - Default all specs. Spec name or group, can list multiple separated by a comma (, )
--                              - "BLOOD", "FDK", "UH", "HAVOC", "VENG", "BALANCE", "FERAL", "GUARDIAN", "RDRUID", "DEVA", "PRES", "AUG", "BM", "MM", "SV", "ARCANE", "FIRE", "FROST", "BREW", "MW", "WW", "HPAL", "PROTPAL", "RET", "DISC", "HPRIEST", "SHADOW", "ASSA", "OUTLAW", "SUB", "ELE", "ENH", "RSHAM", "AFF", "DEMO", "DESTRO", "ARMS", "FURY", "PROTWAR"
--
-- text:          string        - Display custom text
-- showUnitName:  true          - Default false. Displays the name of the unit that the aura is affecting (if exists). Overwrites custom text if enabled.
--                false
--
-- clone:         spellID       - Clones all of the settings from the specified spell Id
-- spellType:    "offensive"    - Defines the type of spell. Will use the associated user-defined border colors and sounds.
--               "defensive"
--               "immunity"
--               "reflect"
--               "cc"
--               "ccImmunity"
--               "utility"
------------------------------------------------------------------------------------------------------------------------------
-- Sound Options
--
-- announce:      "friendly"    - Default is false. Play the spell/aura name
--                "hostile
--
-- customSound:    string       - Play a custom sound effect. Must be the name of a sound file located in
--                              - Media\Sounds\SoundEffects\
------------------------------------------------------------------------------------------------------------------------------
-- Tracking CDs
--
-- cd:           number         - Cooldown of spell to track

addon.profiles.default = {
    ["castStart"] = {
        ["The Hunt"]                        = {spellType="offensive", announce="hostile"},
        ["Arcane Surge"]                    = {spellType="offensive", announce="hostile"},
        ["Frost Bomb"]                      = {spellType="offensive", announce="hostile"},
        ["Snow Drift"]                      = {spellType="offensive", announce="hostile"},
        ["Demolish"]                        = {spellType="offensive", announce="hostile"},

        -- ["Sniper Shot"] = {spellType="offensive", announce="hostile"},
        -- ["Arcane Surge"] = {spellType="offensive", announce="hostile"},
        -- ["Greater Pyroblast"] = {spellType="offensive"},
        -- ["Mindgames"] = {spellType="offensive", announce="hostile"},
        -- ["Soul Rot"] = {spellType="offensive"},
        -- ["Arcanosphere"] = {spellType="offensive"},
        -- ["Drain Life"] = {spellType="defensive"},
        -- ["Mass Dispel"] = {announce="friendly,hostile"},
        -- ["Shattering Throw"] = {announce="friendly,hostile"},
        -- ["Time Skip"] = {"Time Skip"},
    },
    ["castSuccess"] = {
        ["Mass Disintegrate"]               = {spellType="offensive", announce="hostile"},
        ["Ebon Might"]                      = {spellType="offensive", announce="hostile"},
        ["Deep Breath"]                     = {spellType="offensive", announce="hostile"},
        ["Deathmark"]                       = {spellType="offensive", announce="hostile"},
        ["Secret Technique"]                = {spellType="offensive", announce="hostile"},
        ["Cold Blood"]                      = {spellType="offensive", announce="hostile"},
        ["Primordial Wave"]                 = {spellType="offensive", announce="hostile"},
        ["Comet Storm"]                     = {spellType="offensive", announce="hostile"},
        ["Ray of Frost"]                    = {spellType="offensive", announce="hostile"},
        ["Touch of the Magi"]               = {spellType="offensive", announce="hostile"},
        ["Storm, Earth, and Fire"]          = {spellType="offensive", announce="hostile"},
        ["Explosive Shot"]                  = {spellType="offensive", announce="hostile"},
        ["Call of the Wild"]                = {spellType="offensive", announce="hostile"},
        ["Essence Break"]                   = {spellType="offensive", announce="hostile"},
        ["Fel Barrage"]                     = {spellType="offensive", announce="hostile"},
        ["Psyfiend"]                        = {spellType="offensive", announce="hostile"},
        ["Halo"]                            = {spellType="offensive", announce="hostile"},
        ["Entropic Rift"]                   = {spellType="offensive", announce="hostile"},
        ["Summon Demonic Tyrant"]           = {spellType="offensive", announce="hostile"},
        ["Summon Observer"]                 = {spellType="offensive", announce="hostile"},
        ["Dimensional Rift"]                = {spellType="offensive", announce="hostile"},
        ["Soul Rip"]                        = {spellType="offensive", announce="hostile"},
        ["War Banner"]                      = {spellType="offensive", announce="hostile"},
        ["War Breaker"]                     = {spellType="offensive", announce="hostile"},
        ["Skullsplitter"]                   = {spellType="offensive", announce="hostile"},
        ["Feral Frenzy"]                    = {spellType="offensive", announce="hostile"},
        ["Apex Predator"]                   = {spellType="offensive", announce="hostile"},
        ["Solar Beam"]                      = {spellType="cc", announce="hostile"},

        ["Healing Tide Totem"]              = {spellType="defensive", announce="hostile"},
        ["Mana Tide Totem"]                 = {spellType="defensive", announce="hostile"},
        ["Healing Stream Totem"]            = {spellType="defensive", announce="hostile"},
        ["Grounding Totem"]                 = {spellType="defensive", announce="hostile"},
        ["Chrono Loop"]                     = {spellType="defensive", announce="hostile"},
        ["Phase Shift"]                     = {spellType="defensive", announce="hostile"},
        ["Thunderous Roar"]                 = {spellType="defensive", announce="hostile"},
        ["Restitution"]                     = {spellType="defensive", announce="hostile"},
        ["Tranquility"]                     = {spellType="immunity", announce="hostile"},
        ["Abomination Limb"]                = {spellType="offensive", announce="hostile"},
        [383312]                            = {name="Abomination Limb", ignore="true"},
        [383313]                            = {name="Abomination Limb", ignore="true"},
        ["Tip the Scales"]                  = {spellType="offensive", announce="hostile"},
        ["Kidney Shot"]                     = {spellType="cc", announce="hostile"},
        
        ["Gladiator's Medallion"]           = {spellType="defensive", announce="friendly,hostile"},
        ["Vanish"]                          = {spellType="defensive", announce="friendly,hostile"},
        ["Precognition"]                    = {spellType="defensive", announce="friendly,hostile"},
        ["Celestial Conduit"]               = {spellType="offensive", announce="friendly,hostile"},
        ["Void Shift"]                      = {spellType="defensive", announce="friendly,hostile"},
        ["Reaper's Mark"]                   = {spellType="offensive", announce="hostile"},
        
        ["Blessing of Sanctuary"]           = {spellType="defensive", announce="friendly"},

        -- ["Chill Streak"] = {spellType="offensive", announce="hostile"},
        -- ["Dark Transformation"] = {spellType="offensive", announce="hostile"},
        -- ["Summon Gargoyle"] = {spellType="offensive", announce="hostile"},
        -- ["Breath of Sindragosa"] = {spellType="offensive", announce="hostile"},
        -- ["Frostwyrm's Fury"] = {spellType="offensive", announce="hostile"},
        -- ["Anti-Magic Zone"] = {spellType="defensive", announce="friendly"},
        -- ["Fel Barrage"] = {spellType="offensive"},
        -- ["Feral Frenzy"] = {spellType="offensive", announce="hostile"},
        -- ["Fury of Elune"] = {spellType="offensive"},
        -- ["Breath of Eons"] = {spellType="offensive", announce="hostile"},
        -- ["Deep Breath"] = {spellType="offensive", announce="hostile"},
        -- ["Shattering Star"] = {spellType="offensive"},
        -- ["Fury of the Eagle"] = {spellType="offensive"},
        -- ["Call of the Wild"] = {spellType="offensive", announce="hostile"},
        -- ["Touch of the Magi"] = {spellType="offensive", announce="hostile"},
        -- ["Fists of Fury"] = {spellType="offensive"},
        -- ["Invoke Xuen, the White Tiger"] = {spellType="offensive", announce="friendly,hostile"},
        -- ["Storm, Earth, and Fire"] = {"Storm, Earth, and Fire", spellType="offensive", announce="friendly,hostile"},
        -- ["Touch of Karma"] = {spellType="reflect", announce="hostile"},
        -- ["Divine Toll"] = {spellType="offensive"},
        -- ["Psyfiend"] = {spellType="offensive", announce="hostile"},
        -- ["Ray of Frost"] = {spellType="offensive", announce="hostile"},
        -- ["Void Eruption"] = {spellType="offensive", announce="hostile"},
        -- ["Phantom Singularity"] = {spellType="offensive", announce="hostile"},
        -- ["Deathmark"] = {spellType="offensive", announce="hostile"},
        -- ["Secret Technique"] = {spellType="offensive", announce="hostile"},
        -- ["Shiv"] = {spellType="offensive"},
        -- ["Echoing Shock"] = {spellType="offensive"},
        -- ["Skyfury Totem"] = {spellType="offensive"},
        -- ["Fire Elemental"] = {spellType="offensive", announce="hostile"},        
        -- ["Primordial Wave"] = {spellType="offensive", announce="hostile"},
        -- ["Summon Darkglare"] = {spellType="offensive", announce="hostile"},
        -- ["Summon Demonic Tyrant"] = {spellType="offensive", announce="hostile"},
        -- ["Grimoire: Felguard"] = {spellType="offensive", announce="hostile"},
        -- ["Summon Infernal"] = {spellType="offensive", announce="hostile"},
        -- ["Summon Observer"] = {spellType="offensive"},
        -- ["Sharpen Blade"] = {spellType="offensive", announce="hostile"},
        -- ["Spear of Bastion"] = {spellType="offensive"},
        -- ["Tranquility"] = {spellType="immunity"},
        -- ["War Banner"] = {spellType="offensive"},
        -- ["Healing Tide Totem"] = {spellType="defensive", announce="hostile"},
        -- ["Earthen Wall Totem"] = {spellType="defensive", announce="friendly"},
        -- ["Spirit Link Totem"] = {spellType="defensive", announce="friendly"},
        -- ["Rapture"] = {spellType="defensive", announce="friendly"},
        -- ["Restitution"] = {spellType="defensive"},
        -- ["Power Word: Barrier"] = {spellType="defensive", announce="friendly"},
        -- ["Void Shift"] = {spellType="defensive", announce="friendly,hostile", announce="friendly,hostile"},
        -- ["Phase Shift"] = {spellType="defensive"},
        -- ["Demonic Circle"] = {},
        -- ["Demonic Circle: Teleport"] = {announce="friendly,hostile"},
        -- ["Displacement"] = {},
        -- ["Spellsteal"] = {},
        -- ["Transcendence"] = {},
        -- ["Transcendence: Transfer"] = {announce="friendly,hostile"},
        -- ["Vanish"] = {},
        -- ["Shadow Word: Death"] = {},        
        -- ["Drink"] = {announce="hostile"},
    }, 
    ["cooldowns"] = {
        ["Mind Freeze"] = {spellType="cooldown", cd="15"},
        ["Disrupt"] = {spellType="cooldown", cd="15"},
        ["Skull Bash"] = {spellType="cooldown", cd="15"},
        ["Quell"] = {spellType="cooldown", cd="20"},
        ["Counter Shot"] = {spellType="cooldown", cd="24"},
        ["Counterspell"] = {spellType="cooldown", cd="20"},
        ["Rebuke"] = {spellType="cooldown", cd="15"},
        ["Kick"] = {spellType="cooldown", cd="15"},
        ["Spear Hand Strike"] = {spellType="cooldown", cd="15"},
        ["Wind Shear"] = {spellType="cooldown", cd="12"},
        ["Spell Lock"] = {spellType="cooldown", cd="15"},
        ["Optical Blast"] = {spellType="cooldown", cd="15"},
        ["Shadow Lock"] = {spellType="cooldown", cd="15"},
        ["Pummel"] = {spellType="cooldown", cd="14"},
        ["Kidney Shot"] = {spellType="cooldown", cd="30"},
    }, 
    ["auras"] = {
        -- Friendly Defensives
        ["Anti-Magic Shell"]                = {spellType="defensive", announce="friendly"},
        ["Icebound Fortitude"]              = {spellType="defensive", announce="friendly"},
        ["Blur"]                            = {spellType="defensive", announce="friendly"},
        ["Frenzied Regeneration"]           = {spellType="defensive", announce="friendly"},
        ["Survival Instincts"]              = {spellType="defensive", announce="friendly"},
        ["Obsidian Scales"]                 = {spellType="defensive", announce="friendly"},        
        ["Blistering Scales"]               = {spellType="defensive", announce="friendly"},
        ["Survival of the Fittest"]         = {spellType="defensive", announce="friendly"},
        ["Fortifying Brew"]                 = {spellType="defensive", announce="friendly"},
        ["Diffuse Magic"]                   = {spellType="defensive", announce="friendly"},        
        ["Astral Shift"]                    = {spellType="defensive", announce="friendly"},
        ["Dark Pact"]                       = {spellType="defensive", announce="friendly"},
        ["Unending Resolve"]                = {spellType="defensive", announce="friendly"},
        ["Enraged Regeneration"]            = {spellType="defensive", announce="friendly"},

        -- Hostile Auras
        ["Nullifying Shroud"]               = {spellType="ccImmunity", announce="hostile"},
        ["Dragonrage"]                      = {spellType="offensive", announce="hostile"},
        ["Shadow Blades"]                   = {spellType="offensive", announce="hostile"},
        ["Shadow Dance"]                    = {spellType="offensive", announce="hostile"},
        ["Adrenaline Rush"]                 = {spellType="offensive", announce="hostile"},
        ["Unholy Frenzy"]                   = {spellType="offensive", announce="hostile"},        
        ["Pillar of Frost"]                 = {spellType="offensive", announce="hostile"},
        ["Shadowy Duel"]                    = {spellType="offensive", announce="hostile"},
        ["Feral Spirit"]                    = {spellType="offensive", announce="hostile"},
        ["Bloodlust"]                       = {spellType="offensive", announce="hostile"},
        ["Ascendance"]                      = {spellType="offensive", announce="hostile"},
        ["Doom Winds"]                      = {spellType="offensive", announce="hostile"},
        ["Combustion"]                      = {spellType="offensive", announce="hostile"},
        ["Icy Veins"]                       = {spellType="offensive", announce="hostile"},        
        ["Trueshot"]                        = {spellType="offensive", announce="hostile"},
        ["Coordinated Assault"]             = {spellType="offensive", announce="hostile"},
        ["Final Reckoning"]                 = {spellType="offensive", announce="hostile"},
        ["Avenging Wrath"]                  = {spellType="offensive", announce="hostile"},
        ["Dark Ascension"]                  = {spellType="offensive", announce="hostile"},
        ["Power Infusion"]                  = {spellType="offensive", announce="hostile"},
        ["Odyn's Fury"]                     = {spellType="offensive", announce="hostile"},
        ["Recklessness"]                    = {spellType="offensive", announce="hostile"},
        ["Avatar"]                          = {spellType="offensive", announce="hostile"},
        ["Berserk"]                         = {spellType="offensive", announce="hostile"},
        ["Celestial Alignment"]             = {spellType="offensive"},
        ["Incarnation: Avatar of Ashamane"] = {spellType="offensive", announce="hostile"},
        ["Incarnation: Chosen of Elune"]    = {spellType="offensive", announce="hostile"},
        ["Incarnation: King of the Jungle"] = {spellType="offensive", announce="hostile"},
        
        ["Spell Reflection"]                = {spellType="reflect", announce="hostile"},

        -- Friendly and Hostile
        ["Metamorphosis"]                   = {spellType="defensive", announce="friendly,hostile"},
        ["Time Stop"]                       = {spellType="immunity", announce="friendly,hostile"},
        ["Ice Block"]                       = {spellType="immunity", announce="friendly,hostile"},
        ["Blessing of Protection"]          = {spellType="immunity", announce="friendly,hostile"},
        ["Aspect of the Turtle"]            = {spellType="immunity", announce="friendly,hostile"},
        ["Divine Shield"]                   = {spellType="immunity", announce="friendly,hostile"},
        ["Divine Protection"]               = {spellType="immunity", announce="friendly,hostile"},
        ["Evasion"]                         = {spellType="immunity", announce="friendly,hostile"},
        ["Burrow"]                          = {spellType="immunity", announce="friendly,hostile"},
        ["Die by the Sword"]                = {spellType="immunity", announce="friendly,hostile"},
        ["Life Cocoon"]                     = {spellType="immunity", announce="friendly,hostile"},
        ["Glimpse"]                         = {spellType="immunity", announce="friendly,hostile"},
        ["Tranquility"]                     = {spellType="immunity", announce="friendly,hostile"},
        ["Survival Tactics"]                = {spellType="immunity", announce="friendly,hostile"},
        ["Alter Time"]                      = {spellType="immunity", announce="friendly,hostile"},
        ["Dispersion"]                      = {spellType="immunity", announce="friendly,hostile"},
        ["Riposte"]                         = {spellType="immunity", announce="friendly,hostile"},
        ["Ethereal Form"]                   = {spellType="immunity", announce="friendly,hostile"},


        -- ["Abomination Limb"] = {spellType="offensive"},
        -- [383312] = {name="Abomination Limb", ignore="true"},
        -- [383313] = {name="Abomination Limb", ignore="true"},
        -- ["Ghoulish Frenzy"] = {spellType="offensive"},
        -- ["Unholy Assault"] = {spellType="offensive", announce="hostile"},
        -- ["Pillar of Frost"] = {spellType="offensive", announce="hostile"},
        -- ["Remorseless Winter"] = {spellType="offensive"},
        -- ["Demon Soul"] = {spellType="offensive"},
        -- ["Metamorphosis"] = {spellType="offensive", announce="hostile"},
        -- ["Berserk"] = {spellType="offensive", announce="hostile"},
        -- ["Celestial Alignment"] = {spellType="offensive"},
        -- ["Incarnation: Avatar of Ashamane"] = {spellType="offensive", announce="hostile"},
        -- ["Incarnation: Chosen of Elune"] = {spellType="offensive", announce="hostile"},
        -- ["Incarnation: King of the Jungle"] = {spellType="offensive", announce="hostile"},
        -- ["Dragonrage"] = {spellType="offensive", announce="hostile"},
        -- ["Tip the Scales"] = {spellType="offensive", announce="hostile"},
        -- ["Bestial Wrath"] = {spellType="offensive"},
        -- ["Coordinated Assault"] = {spellType="offensive", announce="hostile"},
        -- ["Trueshot"] = {spellType="offensive", announce="hostile"},
        -- ["Combustion"] = {spellType="offensive", announce="hostile"},
        -- ["Icy Veins"] = {spellType="offensive", announce="hostile"},
        -- ["Serenity"] = {spellType="offensive"},
        -- ["Avenging Wrath"] = {spellType="offensive", announce="hostile"},
        -- ["Final Reckoning"] = {spellType="offensive"},
        -- ["Dark Archangel"] = {spellType="offensive"},
        -- ["Dark Archangel"] = {spellType="offensive"},
        -- ["Power Infusion"] = {spellType="offensive", announce="friendly"},
        -- ["Voidform"] = {spellType="offensive"},
        -- ["Adrenaline Rush"] = {spellType="offensive", announce="hostile"},
        -- ["Echoing Reprimand"] = {spellType="offensive"},
        -- ["Shadow Blades"] = {spellType="offensive", announce="hostile"},
        -- ["Shadow Dance"] = {spellType="offensive", announce="hostile"},
        -- ["Ascendance"] = {spellType="offensive", announce="hostile"},
        -- ["Feral Spirit"] = {spellType="offensive", announce="hostile"},
        -- ["Stormkeeper"] = {spellType="offensive"},
        -- ["Dark Soul: Misery"] = {spellType="offensive"},
        -- ["Avatar"] = {spellType="offensive", announce="hostile"},
        -- ["Bladestorm"] = {spellType="offensive"},
        -- ["Death Wish"] = {spellType="offensive"},
        -- ["Recklessness"] = {spellType="offensive", announce="hostile"},
        -- ["Death Pact"] = {spellType="defensive"},
        -- ["Darkness"] = {spellType="defensive", announce="friendly"},
        -- ["Netherwalk"] = {spellType="defensive"},
        -- ["Nether Bond"] = {spellType="defensive"},
        -- ["Rain from Above"] = {spellType="defensive"},
        -- ["Barkskin"] = {spellType="defensive", announce="hostile"},
        -- ["Cenarion Ward"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Ironbark"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Obsidian Scales"] = {spellType="defensive", announce="hostile"},
        -- ["Renewing Blaze"] = {spellType="defensive"},
        -- ["Time Stop"] = {spellType="defensive", announce="hostile"},
        -- ["Fortitude of the Bear"] = {spellType="defensive", announce="hostile"},
        -- ["Interlope"] = {spellType="defensive", announce="hostile"},
        -- ["Roar of Sacrifice"] = {spellType="defensive", announce="hostile"},
        -- ["Survival of the Fittest"] = {spellType="defensive", announce="hostile"},
        -- ["Dampen Harm"] = {spellType="defensive"},
        -- ["Diffuse Magic"] = {spellType="defensive"},
        -- ["Fortifying Brew"] = {spellType="defensive", announce="hostile"},
        -- ["Ardent Defender"] = {spellType="defensive"},
        -- ["Blessing of Sacrifice"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Blessing of Sanctuary"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Guardian of Ancient Kings"] = {spellType="defensive"},
        -- ["Guardian Spirit"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Pain Suppression"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Ray of Hope"] = {spellType="defensive", announce="hostile"},
        -- ["Cloak of Shadows"] = {spellType="defensive"},
        -- ["Astral Shift"] = {spellType="defensive",  announce="hostile"},
                -- ["Dark Pact"] = {spellType="defensive", announce="hostile"},
        -- ["Unending Resolve"] = {spellType="defensive",announce="hostile"},
        -- ["Enraged Regeneration"] = {spellType="defensive", announce="hostile"},
        -- ["Ignore Pain"] = {spellType="defensive"},
        -- ["Last Stand"] = {spellType="defensive"},
        -- ["Rallying Cry"] = {spellType="defensive", announce="hostile"},
        -- ["Shield Wall"] = {spellType="defensive"},
        -- ["Spirit of Redemption"] = {spellType="defensive", announce="friendly,hostile"},
        -- ["Burrow"] = {spellType="immunity", announce="hostile"},
        -- ["Glimpse"] = {spellType="immunity", announce="hostile"},
        -- ["Tranquility"] = {spellType="immunity", announce="hostile"},
        -- ["Aspect of the Turtle"] = {spellType="immunity", announce="hostile"},
        -- ["Survival Tactics"] = {spellType="immunity", announce="hostile"},
        -- ["Alter Time"] = {spellType="immunity", announce="hostile"},
        -- ["Ice Block"] = {spellType="immunity", announce="hostile"},
        -- ["Life Cocoon"] = {spellType="immunity", announce="hostile"},
        -- ["Blessing of Protection"] = {spellType="immunity", announce="hostile"},
        -- ["Divine Shield"] = {spellType="immunity", announce="hostile"},
        -- ["Dispersion"] = {spellType="immunity", announce="hostile"},
        -- ["Riposte"] = {spellType="immunity"},
        -- ["Evasion"] = {spellType="immunity", announce="hostile"},
        -- ["Ethereal Form"] = {spellType="immunity"},
        -- ["Die by the Sword"] = {spellType="immunity", announce="hostile"},
        -- ["Rage of the Sleeper"] = {spellType="reflect", announce="hostile"},
        -- ["Thorns"] = {spellType="reflect", announce="hostile"},
        -- ["Shield of Vengeance"] = {spellType="reflect", announce="hostile"},
        -- ["Spell Reflection"] = {spellType="reflect", announce="hostile"},
        -- ["Blistering Scales"] = {spellType="reflect", announce="hostile"},
        -- ["Steel Trap"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        -- ["Earthgrab Totem"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        -- ["Entangling Roots"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        -- ["Entrapment"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        -- ["Freeze"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        -- ["Frost Nova"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        -- ["Ice Nova"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        -- ["Landslide"] = {spellType="cc", nameplate="true", npcDuration="15", playerDuration="6"},
        -- ["Mass Entanglement"] = {spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        -- ["Nature's Grasp"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        -- ["Tracker's Net"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        -- ["Freezing Trap"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Diamond Ice"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Gouge"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- ["Hibernate"] = {spellType="cc", nameplate="true", npcDuration="40", playerDuration="6"},
        -- ["Holy Word: Chastise"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Imprison"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        -- ["Detainment"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="6"},
        -- ["Incapacitating Roar"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        -- ["Mortal Coil"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        -- ["Paralysis"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="4"},
        -- ["Quaking Palm"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="2"},
        -- ["Sap"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        -- ["Scatter Shot"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Shackle Undead"] = {spellType="cc", nameplate="true", npcDuration="50", playerDuration="5"},
        -- ["Hex"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        -- ["Polymorph"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        -- ["Repentance"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="6"},
        -- ["Ring of Frost"] = {spellType="cc", nameplate="true", npcDuration="10", playerDuration="6"},
        -- [321329] = {name="Ring of Frost Slow", ignore=true},
        -- ["Blind"] = {spellType="cc", nameplate="true", npcDuration="60", playerDuration="5"},
        -- ["Blinding Light"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="4"},
        -- ["Blinding Sleet"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        -- [317898] = {name="Blinding Sleet Slow", ignore=true},
        -- ["Dragon's Breath"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- ["Intimidating Shout"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="5"},
        -- ["Psychic Scream"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        -- ["Seduction"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        -- ["Sigil of Misery"] = {spellType="cc", nameplate="true", npcDuration="15", playerDuration="3"},
        -- [207684] = {name="Sigil of Misery Pre-fear circle", ignore=true},
        -- ["Cyclone"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="6"},
        -- ["Fear"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="6"},
        -- ["Mind Control"] = {spellType="cc", nameplate="true", npcDuration="30", playerDuration="6"},
        -- ["Sleep Walk"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="4"},
        -- ["Song of Chi-Ji"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},
        -- ["Scare Beast"] = {spellType="cc", nameplate="true", npcDuration="20", playerDuration="5"},        
        -- ["Rake"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- [155722] = {name="Rake DoT", ignore="true"},        
        -- ["Axe Toss"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Capicator Totem"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        -- ["Chaos Nova"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        -- ["Cheap Shot"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- ["Fel Eruption"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Gnaw"] = {spellType="cc", nameplate="true", npcDuration="1", playerDuration="1"},
        -- ["Hammer of Justice"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="5"},
        -- ["Haymaker"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="2"},
        -- ["Intimidation"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="3"},
        -- [117526] = {name="Binding Shot Stun", spellType="cc", nameplate="true", npcDuration="5", playerDuration="3"},
        -- ["Consecutive Concussion"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},        
        -- ["Kidney Shot"] = {spellType="cc", nameplate="true", npcDuration="6", playerDuration="5", announce="hostile"},
        -- ["Leg Sweep"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        -- ["Lightning Lasso"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Maim"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="4"},
        -- ["Mighty Bash"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- ["Psychic Horror"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Shockwave"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},
        -- ["Storm Bolt"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["War Stomp"] = {spellType="cc", nameplate="true", npcDuration="2", playerDuration="2"},        
        -- ["Shadowfury"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        -- ["Garrote"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},
        -- [202137] = {name="Sigil of Silence Pre-cast Circle", ignore=true},
        -- ["Sigil of Silence"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="3"},
        -- ["Silence"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="4"},
        -- ["Solar Beam"] = {spellType="cc", nameplate="true", npcDuration="8", playerDuration="6"},
        -- ["Spider Venom"] = {spellType="cc", nameplate="true", npcDuration="3", playerDuration="3"},        
        -- ["Disarm"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Dismantle"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Faerie Swarm"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Grapple Weapon"] = {spellType="cc", nameplate="true", npcDuration="5", playerDuration="5"},
        -- ["Sticky Tar Bomb"] = {spellType="cc", nameplate="true", npcDuration="4", playerDuration="5"},
        -- ["Lichborne"] = {spellType="ccImmunity"},
        -- ["Nullifying Shroud"] = {spellType="ccImmunity", announce="hostile"},
        -- ["Zen Focus Tea"] = {spellType="ccImmunity"},
        -- ["Holy Ward"] = {spellType="ccImmunity", announce="hostile"},
        -- ["Grounding Totem"] = {spellType="ccImmunity", announce="hostile"},
        -- ["Nether Ward"] = {spellType="ccImmunity", announce="hostile"},
        -- ["Spectral Sight"] = {spellType="utility", announce="hostile"},
        -- ["Time Spiral"] = {spellType="utility", announce="hostile"},
        -- ["Shadowy Duel"] = {spellType="utility", announce="hostile"},
        -- ["Camouflage"] = {spellType="utility", announce="hostile"},
        -- ["Greater Invisibility"] = {spellType="utility", announce="hostile"},
        -- ["Invisibility"] = {spellType="utility", announce="hostile"},
        -- ["Mass Invisibility"] = {spellType="utility", announce="hostile"},
        -- ["Prowl"] = {spellType="utility", announce="hostile"},
        -- ["Shadowmeld"] = {spellType="utility", announce="hostile"},
        -- ["Stealth"] = {spellType="utility", announce="hostile"},
        -- ["Blessing of Freedom"] = {spellType="utility", announce="hostile"},
        -- ["Master's Call"] = {spellType="utility", announce="hostile"},
    },
    ["bars"] = {
        ["primary-friendly"] = {
            ["displayName"] = "Friendly Spells", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -209, 
                ["yOfs"] = -162, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["primary-hostile"] = {
            ["displayName"] = "Enemy Spells", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 209, 
                ["yOfs"] = -162, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 30, 
                ["borderSize"] = 2, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 5, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 6, 
                ["padding"] = 6, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        },
        ["cooldowns-friendly"] = {
            ["displayName"] = "Friendly Cooldowns", 
            ["refreshRate"] = .1,                
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = -200, 
                ["yOfs"] = -117, 
            }, 
            ["icons"] = {
                ["align"] = "RIGHT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = false, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }, 
        ["cooldowns-hostile"] = {
            ["displayName"] = "Enemy Cooldowns", 
            ["refreshRate"] = .1, 
            ["animationTime"] = 1, 
            ["maxSpellQueue"] = 100, 
            ["clampedToScreen"] = true, 
            ["strata"] = "LOW", 
            ["position"] = {
                ["anchorPoint"] = "CENTER", 
                ["relativeTo"] = "UIParent", 
                ["relativePoint"] = "CENTER", 
                ["xOfs"] = 200, 
                ["yOfs"] = -117, 
            }, 
            ["icons"] = {
                ["align"] = "LEFT", 
                ["size"] = 28, 
                ["borderSize"] = 1, 
                ["borderColor"] = {0, 0, 0, .6}, 
                ["backdropSize"] = 1, 
                ["backdropColor"] = {0, 0, 0, .4}, 
                ["innerBorder"] = true, 
                ["innerBorderColor"] = {0, 0, 0, .9}, 
                ["font"] = "GameFontNormal", 
                ["ellipsis"] = true, 
                ["zoom"] = true, 
                ["max"] = 8, 
                ["padding"] = 3, 
                ["showCooldown"] = true, 
                ["cooldownCounter"] = true, 
                ["cooldownFontSize"] = 18, 
                ["cooldownFontColor"] = {1, 1, 0, 1}, 
                ["endAnimationTime"] = 1, 
                ["swipeAlpha"] = .3, 
                ["showTooltips"] = true, 
            }
        }
    }
}
